### ISSUE TITLE
Create guide for beginners

### ISSUE THREAD

**Issue by asdsyd** [learnbyexample/learn_gnused#2]
Many of us are here mostly because we chose Linux as a subject to learn in our college. And now it requires us to learn and get comfortable with sed but I find no guide on how to correctly utilise such repository.

Like how am I supposed to learn? Should I fork and make changes in the exercise section or copy input codes to feed my terminal and practise? but I would like to keep a track of my achievements and progress of learning sed.
This would be very helpful and appreciated. 
Thank you.

**Comment by learnbyexample** [comment]
Hello.

This repository includes the markdown source and files used in the ebook. To read the ebook, you can visit https://learnbyexample.github.io/learn_gnused/. For learning purposes, you are meant to practice from your terminal. Cloning (or downloading) the repo would provide you the files used in the examples/exercises.

If you want to get started with Linux before using sed, check out my basics book https://learnbyexample.github.io/cli-computing/ and this curated list of resources https://learnbyexample.github.io/curated_resources/linux_cli_scripting.html.

Since my resources are only ebooks, there isn't any interactive way to keep track of your progress. You'll have to do that manually or use some other resource.

**Comment by asdsyd** [comment]
Alright. Thanks!
